spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      # 可选配置
      timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
